export const PUSH_LOGIN   = "PUSH_LOGIN"
export const PUSH_SETTING = "PUSH_SETTING"

export const HOME_POST_REQUEST_SUCCESS = "HOME_POST_REQUEST_SUCCESS"
export const HOME_POST_REQUEST         = "HOME_POST_REQUEST"
export const HOME_POST_REQUEST_FAILURE = "HOME_POST_REQUEST_FAILURE"

export const FINANCE_POST_REQUEST         = "FINANCE_POST_REQUEST"
export const FINANCE_POST_REQUEST_SUCCESS = "FINANCE_POST_REQUEST_SUCCESS"
export const FINANCE_POST_REQUEST_FAILURE = "FINANCE_POST_REQUEST_FAILURE"

export const MINE_POST_REQUEST         = "MINE_POST_REQUEST"
export const MINE_POST_REQUEST_SUCCESS = "MINE_POST_REQUEST_SUCCESS"
export const MINE_POST_REQUEST_FAILURE = "MINE_POST_REQUEST_FAILURE"

export const LOGIN_POST_REQUEST         = "LOGIN_POST_REQUEST"
export const LOGIN_POST_REQUEST_SUCCESS = "LOGIN_POST_REQUEST_SUCCESS"
export const LOGIN_POST_REQUEST_FAILURE = "LOGIN_POST_REQUEST_FAILURE"